# Generated by Django 3.1.5 on 2021-01-07 05:16

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aplicatie2', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExtend',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicatie2.companies')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('created', 'created'), ('updated', 'updated'), ('refresh', 'refresh')], max_length=10, verbose_name='Action')),
                ('url', models.CharField(max_length=100, verbose_name='URL')),
                ('departament', models.CharField(max_length=100, verbose_name='Departament')),
                ('rol', models.CharField(max_length=100, verbose_name='Rol')),
                ('zile_concediu', models.CharField(max_length=100, verbose_name='Zile Concediu')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicatie2.companies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.userextend')),
            ],
        ),
    ]
